name: Bug report
description: Report a bug
title: A brief description of the bug
labels: [bug 🐛]
body:
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Pixeval's version
      options:
        - WinUI3
        - WPF
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description of the problem
      description: Please describe the bug concisely and completely. You can attach the code that went wrong if you know
  - type: textarea
    attributes:
      label: Screenshot
      description: If possible, attach a screenshot when the error occurred
  - type: textarea
    attributes:
      label: Error code
      description: If possible, attach the full error code and exception stack trace
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Windows major version
      description: Major version of Windows
      multiple: true
      options:
        - Windows 11
        - Windows 10
        - Earlier than Windows 10 (not supported in WinUI3)
  - type: dropdown
    attributes:
      label: Specific Windows version
      description: If you know about this, please provide a more specific version
      multiple: true
      options:
        - Insider Build
        - Windows 11 22H2 (22621)
        - Windows 11 21H2 (22000)
        - November 2021 Update/21H2 (19044)
        - May 2021 Update/21H1 (19043)
        - October 2020 Update/20H2 (19042)
        - October 2018 Update/RS5 (17763)
        - Windows 8.1
        - Windows 8
        - Windows 7
        - Windows Vista
        - Windows XP and earlier
  - type: textarea
    attributes:
      label: Additional Information
      description: Any additional information you would like to provide
