name: CI

on:
    push:
    pull_request:
  

jobs:
    build:
        runs-on: windows-latest

        env:
            Solution_Name: ./Pixeval.sln
            Project_Path: ./src/Pixeval/Pixeval.csproj
            Configuration: Release

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1.8.1
              with:
                  dotnet-version: '5.0.400'

            - name: Cache nuget packages
              id: cache-nuget
              uses: actions/cache@v2
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/Pixeval.csproj') }}
                  restore-keys: |
                      ${{ runner.os }}-nuget-

            - name: Restore the application
              run: dotnet restore

            - name: Publish the application
              run: dotnet publish "src\Pixeval (Package)\Pixeval (Package).wapproj" -p:OutDir="$PWD/publish" -c $env:Configuration

            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: Pixeval
                  path: "./publish/*"
