name: CI

on:
    push:
    pull_request:
  

jobs:
    build:
        runs-on: windows-latest

        env:
            Solution_Name: ./Pixeval.sln
            Project_Path: ./src/Pixeval/Pixeval.csproj
            Configuration: Release

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  
            - name: setup-msbuild
              uses: microsoft/setup-msbuild@v1
              
            - name: Cache nuget packages
              id: cache-nuget
              uses: actions/cache@v2
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/Pixeval.csproj') }}
                  restore-keys: |
                      ${{ runner.os }}-nuget-

            - name: Restore the application
              run: msbuild -t:restore

            - name: Publish the application
              run:  msbuild -t:publish -p:PublishDir="$PWD/publish" -c $env:Configuration

            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: Pixeval
                  path: "./publish/*"
