name: CI

on:
    push:
    pull_request:
  

jobs:
    build:
        strategy:
            matrix:
                platform: [¡®x64¡¯,'x86','arm64']

        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  
            - name: setup-msbuild
              uses: microsoft/setup-msbuild@v1
              
            - name: Restore the application
              run: msbuild -t:restore -p:Platform=${{ matrix.platform }}

            - name: Publish the application
              run:  msbuild '.\src\Pixeval (Package)\Pixeval (Package).wapproj' -t:build -p:Configuration=Release -p:Platform=${{ matrix.platform }}

            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: Pixeval
                  path: "./src/Pixeval (Package)/AppPackages/*"
