name: CI

on:
    push:
    pull_request:
  

jobs:
    build:
        strategy:
            matrix:
                platform: ['x64','x86','arm64']

        runs-on: windows-2022

        env:
            private_key: ${{ secrets.PRIVATE_KEY }}
        steps:
            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1.9.0
              with:
                dotnet-version: '6.0.100'
                include-prerelease: true
  
            - name: Checkout
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
                  
            - name: setup-msbuild
              uses: microsoft/setup-msbuild@v1
            - name: Get pfx
              run: '[io.file]::WriteAllBytes("./temp.pfx",[convert]::FromBase64String($env:private_key))'
              shell: pwsh

            - name: Restore the application
              run: msbuild -t:restore -p:Platform=${{ matrix.platform }}

            - name: Publish the application
              run:  msbuild -t:publish -p:Configuration=Release -p:Platform=${{ matrix.platform }} -p:GenerateAppxPackageOnBuild=true -p:PackageCertificateKeyFile="./temp.pfx"
            - name: Remove pfx
              run: rm ./temp.pfx
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: Pixeval
                  path: "./src/Pixeval/AppPackages/*"
